spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      compression-type: lz4
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #value-serializer: com.dadagum.kafka.commons.serializer.MessageSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: hongda-input
